#!/usr/bin/env bun
/**
 * Renders the email examples to HTML so the docs can show them.
 *
 * Rendering in Node rather than the browser is a size decision, not a taste
 * one. `@react-email/render` statically imports `prettier/standalone` and
 * `prettier/plugins/html`, so bundling it for the client pulls several hundred
 * kilobytes of formatter into a documentation page to draw a static email.
 * Here prettier runs once at build time and never ships.
 *
 * It is also the more honest preview: what lands in the page is the markup a
 * mail client would actually receive, not a React tree approximating it.
 *
 * Run: bun scripts/generate-email-previews.ts
 */

import { writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { render } from '@react-email/render';
import { emailExamples } from '../site/demos/email-examples';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const OUTPUT = join(ROOT, 'site', 'demos', 'email-previews.generated.ts');

const entries: Array<[string, string]> = [];

for (const [id, element] of Object.entries(emailExamples)) {
  // `pretty` keeps the markup readable for anyone who opens the iframe, and
  // costs nothing at runtime because this is the only place it runs.
  const html = await render(element, { pretty: true });
  entries.push([id, html]);
}

const file = `// @generated by scripts/generate-email-previews.ts. DO NOT EDIT.
//
// Email examples rendered to the HTML a mail client receives. Regenerated by
// \`bun run email:generate\`; edit site/demos/email-examples.tsx instead.

export const emailPreviews: Record<string, string> = ${JSON.stringify(
  Object.fromEntries(entries),
  null,
  2,
)};
`;

await writeFile(OUTPUT, file, 'utf8');

const total = entries.reduce((sum, [, html]) => sum + html.length, 0);
console.log(
  `Rendered ${entries.length} email examples\n` +
    `  ${(total / 1024).toFixed(1)} KB of HTML, shipped as a string rather than a renderer\n` +
    `  ${entries.map(([id]) => id).join(', ')}`,
);
